export const COUNTRY_DATA = [
 
//    AFRICA_COUNTRIES  

  { name: "Algeria", code: "+213", iso: "DZ", limit: 9 },
  { name: "Angola", code: "+244", iso: "AO", limit: 9 },
  { name: "Benin", code: "+229", iso: "BJ", limit: 8 },
  { name: "Botswana", code: "+267", iso: "BW", limit: 8 },
  { name: "Burkina Faso", code: "+226", iso: "BF", limit: 8 },
  { name: "Burundi", code: "+257", iso: "BI", limit: 8 },
  { name: "Cabo Verde", code: "+238", iso: "CV", limit: 7 },
  { name: "Cameroon", code: "+237", iso: "CM", limit: 9 },
  { name: "Central African Republic", code: "+236", iso: "CF", limit: 8 },
  { name: "Chad", code: "+235", iso: "TD", limit: 8 },
  { name: "Comoros", code: "+269", iso: "KM", limit: 7 },
  { name: "Congo (Brazzaville)", code: "+242", iso: "CG", limit: 9 },
  { name: "Congo (Kinshasa)", code: "+243", iso: "CD", limit: 9 },
  { name: "Djibouti", code: "+253", iso: "DJ", limit: 8 },
  { name: "Egypt", code: "+20", iso: "EG", limit: 10 },
  { name: "Equatorial Guinea", code: "+240", iso: "GQ", limit: 9 },
  { name: "Eritrea", code: "+291", iso: "ER", limit: 7 },
  { name: "Eswatini", code: "+268", iso: "SZ", limit: 8 },
  { name: "Ethiopia", code: "+251", iso: "ET", limit: 9 },
  { name: "Gabon", code: "+241", iso: "GA", limit: 7 },
  { name: "Gambia", code: "+220", iso: "GM", limit: 7 },
  { name: "Ghana", code: "+233", iso: "GH", limit: 9 },
  { name: "Guinea", code: "+224", iso: "GN", limit: 9 },
  { name: "Guinea-Bissau", code: "+245", iso: "GW", limit: 7 },
  { name: "Ivory Coast", code: "+225", iso: "CI", limit: 10 },
  { name: "Kenya", code: "+254", iso: "KE", limit: 9 },
  { name: "Lesotho", code: "+266", iso: "LS", limit: 8 },
  { name: "Liberia", code: "+231", iso: "LR", limit: 8 },
  { name: "Libya", code: "+218", iso: "LY", limit: 9 },
  { name: "Madagascar", code: "+261", iso: "MG", limit: 9 },
  { name: "Malawi", code: "+265", iso: "MW", limit: 9 },
  { name: "Mali", code: "+223", iso: "ML", limit: 8 },
  { name: "Mauritania", code: "+222", iso: "MR", limit: 8 },
  { name: "Mauritius", code: "+230", iso: "MU", limit: 7 },
  { name: "Morocco", code: "+212", iso: "MA", limit: 9 },
  { name: "Mozambique", code: "+258", iso: "MZ", limit: 9 },
  { name: "Namibia", code: "+264", iso: "NA", limit: 9 },
  { name: "Niger", code: "+227", iso: "NE", limit: 8 },
  { name: "Nigeria", code: "+234", iso: "NG", limit: 10 },
  { name: "Rwanda", code: "+250", iso: "RW", limit: 9 },
  { name: "Sao Tome and Principe", code: "+239", iso: "ST", limit: 7 },
  { name: "Senegal", code: "+221", iso: "SN", limit: 9 },
  { name: "Seychelles", code: "+248", iso: "SC", limit: 7 },
  { name: "Sierra Leone", code: "+232", iso: "SL", limit: 8 },
  { name: "Somalia", code: "+252", iso: "SO", limit: 8 },
  { name: "South Africa", code: "+27", iso: "ZA", limit: 9 },
  { name: "South Sudan", code: "+211", iso: "SS", limit: 9 },
  { name: "Sudan", code: "+249", iso: "SD", limit: 9 },
  { name: "Tanzania", code: "+255", iso: "TZ", limit: 9 },
  { name: "Togo", code: "+228", iso: "TG", limit: 8 },
  { name: "Tunisia", code: "+216", iso: "TN", limit: 8 },
  { name: "Uganda", code: "+256", iso: "UG", limit: 9 },
  { name: "Zambia", code: "+260", iso: "ZM", limit: 9 },
  { name: "Zimbabwe", code: "+263", iso: "ZW", limit: 9 },

//   ASIA_COUNTRIES

{ name: "Afghanistan", code: "+93", iso: "AF", limit: 9 },
  { name: "Armenia", code: "+374", iso: "AM", limit: 8 },
  { name: "Azerbaijan", code: "+994", iso: "AZ", limit: 9 },
  { name: "Bahrain", code: "+973", iso: "BH", limit: 8 },
  { name: "Bangladesh", code: "+880", iso: "BD", limit: 10 },
  { name: "Bhutan", code: "+975", iso: "BT", limit: 8 },
  { name: "Brunei", code: "+673", iso: "BN", limit: 7 },
  { name: "Cambodia", code: "+855", iso: "KH", limit: 9 },
  { name: "China", code: "+86", iso: "CN", limit: 11 },
  { name: "Cyprus", code: "+357", iso: "CY", limit: 8 },
  { name: "Georgia", code: "+995", iso: "GE", limit: 9 },
  { name: "Hong Kong", code: "+852", iso: "HK", limit: 8 },
  { name: "India", code: "+91", iso: "IN", limit: 10 },
  { name: "Indonesia", code: "+62", iso: "ID", limit: 12 },
  { name: "Iran", code: "+98", iso: "IR", limit: 10 },
  { name: "Iraq", code: "+964", iso: "IQ", limit: 10 },
  { name: "Israel", code: "+972", iso: "IL", limit: 9 },
  { name: "Japan", code: "+81", iso: "JP", limit: 10 },
  { name: "Jordan", code: "+962", iso: "JO", limit: 9 },
  { name: "Kazakhstan", code: "+7", iso: "KZ", limit: 10 },
  { name: "Kuwait", code: "+965", iso: "KW", limit: 8 },
  { name: "Kyrgyzstan", code: "+996", iso: "KG", limit: 9 },
  { name: "Laos", code: "+856", iso: "LA", limit: 10 },
  { name: "Lebanon", code: "+961", iso: "LB", limit: 8 },
  { name: "Macao", code: "+853", iso: "MO", limit: 8 },
  { name: "Malaysia", code: "+60", iso: "MY", limit: 9 },
  { name: "Maldives", code: "+960", iso: "MV", limit: 7 },
  { name: "Mongolia", code: "+976", iso: "MN", limit: 8 },
  { name: "Myanmar", code: "+95", iso: "MM", limit: 9 },
  { name: "Nepal", code: "+977", iso: "NP", limit: 10 },
  { name: "North Korea", code: "+850", iso: "KP", limit: 10 },
  { name: "Oman", code: "+968", iso: "OM", limit: 8 },
  { name: "Pakistan", code: "+92", iso: "PK", limit: 10 },
  { name: "Palestine", code: "+970", iso: "PS", limit: 9 },
  { name: "Philippines", code: "+63", iso: "PH", limit: 10 },
  { name: "Qatar", code: "+974", iso: "QA", limit: 8 },
  { name: "Saudi Arabia", code: "+966", iso: "SA", limit: 9 },
  { name: "Singapore", code: "+65", iso: "SG", limit: 8 },
  { name: "South Korea", code: "+82", iso: "KR", limit: 10 },
  { name: "Sri Lanka", code: "+94", iso: "LK", limit: 9 },
  { name: "Syria", code: "+963", iso: "SY", limit: 9 },
  { name: "Taiwan", code: "+886", iso: "TW", limit: 9 },
  { name: "Tajikistan", code: "+992", iso: "TJ", limit: 9 },
  { name: "Thailand", code: "+66", iso: "TH", limit: 9 },
  { name: "Timor-Leste", code: "+670", iso: "TL", limit: 7 },
  { name: "Turkey", code: "+90", iso: "TR", limit: 10 },
  { name: "Turkmenistan", code: "+993", iso: "TM", limit: 8 },
  { name: "United Arab Emirates", code: "+971", iso: "AE", limit: 9 },
  { name: "Uzbekistan", code: "+998", iso: "UZ", limit: 9 },
  { name: "Vietnam", code: "+84", iso: "VN", limit: 9 },
  { name: "Yemen", code: "+967", iso: "YE", limit: 9 },

    // EUROPE_COUNTRIES

  { name: "Albania", code: "+355", iso: "AL", limit: 9 },
  { name: "Andorra", code: "+376", iso: "AD", limit: 6 },
  { name: "Austria", code: "+43", iso: "AT", limit: 10 },
  { name: "Belarus", code: "+375", iso: "BY", limit: 9 },
  { name: "Belgium", code: "+32", iso: "BE", limit: 9 },
  { name: "Bosnia and Herzegovina", code: "+387", iso: "BA", limit: 8 },
  { name: "Bulgaria", code: "+359", iso: "BG", limit: 9 },
  { name: "Croatia", code: "+385", iso: "HR", limit: 9 },
  { name: "Czech Republic", code: "+420", iso: "CZ", limit: 9 },
  { name: "Denmark", code: "+45", iso: "DK", limit: 8 },
  { name: "Estonia", code: "+372", iso: "EE", limit: 8 },
  { name: "Finland", code: "+358", iso: "FI", limit: 9 },
  { name: "France", code: "+33", iso: "FR", limit: 9 },
  { name: "Germany", code: "+49", iso: "DE", limit: 11 },
  { name: "Greece", code: "+30", iso: "GR", limit: 10 },
  { name: "Hungary", code: "+36", iso: "HU", limit: 9 },
  { name: "Iceland", code: "+354", iso: "IS", limit: 7 },
  { name: "Ireland", code: "+353", iso: "IE", limit: 9 },
  { name: "Italy", code: "+39", iso: "IT", limit: 10 },
  { name: "Latvia", code: "+371", iso: "LV", limit: 8 },
  { name: "Liechtenstein", code: "+423", iso: "LI", limit: 7 },
  { name: "Lithuania", code: "+370", iso: "LT", limit: 8 },
  { name: "Luxembourg", code: "+352", iso: "LU", limit: 9 },
  { name: "Malta", code: "+356", iso: "MT", limit: 8 },
  { name: "Moldova", code: "+373", iso: "MD", limit: 8 },
  { name: "Monaco", code: "+377", iso: "MC", limit: 8 },
  { name: "Montenegro", code: "+382", iso: "ME", limit: 8 },
  { name: "Netherlands", code: "+31", iso: "NL", limit: 9 },
  { name: "North Macedonia", code: "+389", iso: "MK", limit: 8 },
  { name: "Norway", code: "+47", iso: "NO", limit: 8 },
  { name: "Poland", code: "+48", iso: "PL", limit: 9 },
  { name: "Portugal", code: "+351", iso: "PT", limit: 9 },
  { name: "Romania", code: "+40", iso: "RO", limit: 9 },
  { name: "Russia", code: "+7", iso: "RU", limit: 10 },
  { name: "San Marino", code: "+378", iso: "SM", limit: 10 },
  { name: "Serbia", code: "+381", iso: "RS", limit: 9 },
  { name: "Slovakia", code: "+421", iso: "SK", limit: 9 },
  { name: "Slovenia", code: "+386", iso: "SI", limit: 8 },
  { name: "Spain", code: "+34", iso: "ES", limit: 9 },
  { name: "Sweden", code: "+46", iso: "SE", limit: 9 },
  { name: "Switzerland", code: "+41", iso: "CH", limit: 9 },
  { name: "Ukraine", code: "+380", iso: "UA", limit: 9 },
  { name: "United Kingdom", code: "+44", iso: "GB", limit: 10 },
  { name: "Vatican City", code: "+39", iso: "VA", limit: 10 },

//   NORTH AMERICA (23 Countries)

{ name: "Antigua and Barbuda", code: "+1", iso: "AG", limit: 10 },
  { name: "Bahamas", code: "+1", iso: "BS", limit: 10 },
  { name: "Barbados", code: "+1", iso: "BB", limit: 10 },
  { name: "Belize", code: "+501", iso: "BZ", limit: 7 },
  { name: "Canada", code: "+1", iso: "CA", limit: 10 },
  { name: "Costa Rica", code: "+506", iso: "CR", limit: 8 },
  { name: "Cuba", code: "+53", iso: "CU", limit: 8 },
  { name: "Dominica", code: "+1", iso: "DM", limit: 10 },
  { name: "Dominican Republic", code: "+1", iso: "DO", limit: 10 },
  { name: "El Salvador", code: "+503", iso: "SV", limit: 8 },
  { name: "Grenada", code: "+1", iso: "GD", limit: 10 },
  { name: "Guatemala", code: "+502", iso: "GT", limit: 8 },
  { name: "Haiti", code: "+509", iso: "HT", limit: 8 },
  { name: "Honduras", code: "+504", iso: "HN", limit: 8 },
  { name: "Jamaica", code: "+1", iso: "JM", limit: 10 },
  { name: "Mexico", code: "+52", iso: "MX", limit: 10 },
  { name: "Nicaragua", code: "+505", iso: "NI", limit: 8 },
  { name: "Panama", code: "+507", iso: "PA", limit: 8 },
  { name: "Saint Kitts and Nevis", code: "+1", iso: "KN", limit: 10 },
  { name: "Saint Lucia", code: "+1", iso: "LC", limit: 10 },
  { name: "Saint Vincent and the Grenadines", code: "+1", iso: "VC", limit: 10 },
  { name: "Trinidad and Tobago", code: "+1", iso: "TT", limit: 10 },
  { name: "United States", code: "+1", iso: "US", limit: 10 },

//   SOUTH AMERICA (12 Countries)

{ name: "Argentina", code: "+54", iso: "AR", limit: 10 },
  { name: "Bolivia", code: "+591", iso: "BO", limit: 8 },
  { name: "Brazil", code: "+55", iso: "BR", limit: 11 },
  { name: "Chile", code: "+56", iso: "CL", limit: 9 },
  { name: "Colombia", code: "+57", iso: "CO", limit: 10 },
  { name: "Ecuador", code: "+593", iso: "EC", limit: 9 },
  { name: "Guyana", code: "+592", iso: "GY", limit: 7 },
  { name: "Paraguay", code: "+595", iso: "PY", limit: 9 },
  { name: "Peru", code: "+51", iso: "PE", limit: 9 },
  { name: "Suriname", code: "+597", iso: "SR", limit: 7 },
  { name: "Uruguay", code: "+598", iso: "UY", limit: 8 },
  { name: "Venezuela", code: "+58", iso: "VE", limit: 10 },


//   OCEANIA_COUNTRIES

  { name: "Australia", code: "+61", iso: "AU", limit: 9 },
  { name: "Fiji", code: "+679", iso: "FJ", limit: 7 },
  { name: "Kiribati", code: "+686", iso: "KI", limit: 8 },
  { name: "Marshall Islands", code: "+692", iso: "MH", limit: 7 },
  { name: "Micronesia", code: "+691", iso: "FM", limit: 7 },
  { name: "Nauru", code: "+674", iso: "NR", limit: 7 },
  { name: "New Zealand", code: "+64", iso: "NZ", limit: 9 },
  { name: "Palau", code: "+680", iso: "PW", limit: 7 },
  { name: "Papua New Guinea", code: "+675", iso: "PG", limit: 8 },
  { name: "Samoa", code: "+685", iso: "WS", limit: 7 },
  { name: "Solomon Islands", code: "+677", iso: "SB", limit: 7 },
  { name: "Tonga", code: "+676", iso: "TO", limit: 7 },
  { name: "Tuvalu", code: "+688", iso: "TV", limit: 5 },
  { name: "Vanuatu", code: "+678", iso: "VU", limit: 7 }

  



];